[
  {
    info: {
      satname: "NOAA 15",
      satid: 25338,
      transactionscount: 605,
    },
    positions: [
      {
        satlatitude: 68.68891437,
        satlongitude: -53.29842969,
        sataltitude: 808.06,
        azimuth: 342.53,
        elevation: -34.53,
        ra: 236.12925091,
        dec: 51.89031239,
        timestamp: 1713356803,
        eclipsed: false,
      },
      {
        satlatitude: 68.63470941,
        satlongitude: -53.36909574,
        sataltitude: 808.05,
        azimuth: 342.47,
        elevation: -34.53,
        ra: 236.20887731,
        dec: 51.87074442,
        timestamp: 1713356804,
        eclipsed: false,
      },
    ],
  },
  {
    info: {
      satname: "SPACE STATION",
      satid: 25544,
      transactionscount: 605,
    },
    positions: [
      {
        satlatitude: 44.92510328,
        satlongitude: -8.30190847,
        sataltitude: 417.89,
        azimuth: 351.71,
        elevation: -18.44,
        ra: 236.32625656,
        dec: 69.86807347,
        timestamp: 1713356803,
        eclipsed: false,
      },
      {
        satlatitude: 44.89361859,
        satlongitude: -8.22645598,
        sataltitude: 417.89,
        azimuth: 351.78,
        elevation: -18.41,
        ra: 236.19981571,
        dec: 69.91702213,
        timestamp: 1713356804,
        eclipsed: false,
      },
    ],
  },
  {
    info: {
      satname: "NOAA 19",
      satid: 33591,
      transactionscount: 605,
    },
    positions: [
      {
        satlatitude: -42.07772422,
        satlongitude: -57.37213327,
        sataltitude: 870.57,
        azimuth: 223.18,
        elevation: -27.65,
        ra: 264.99765648,
        dec: -40.19569655,
        timestamp: 1713356803,
        eclipsed: false,
      },
      {
        satlatitude: -42.1351045,
        satlongitude: -57.39299484,
        sataltitude: 870.6,
        azimuth: 223.13,
        elevation: -27.67,
        ra: 264.94950982,
        dec: -40.22620696,
        timestamp: 1713356804,
        eclipsed: false,
      },
    ],
  },
  {
    info: {
      satname: "NOAA 18",
      satid: 28654,
      transactionscount: 605,
    },
    positions: [
      {
        satlatitude: -66.2507113,
        satlongitude: 173.85132956,
        sataltitude: 868.79,
        azimuth: 177.29,
        elevation: -54.53,
        ra: 210.53407483,
        dec: -35.3403315,
        timestamp: 1713356803,
        eclipsed: true,
      },
      {
        satlatitude: -66.19655584,
        satlongitude: 173.79185803,
        sataltitude: 868.78,
        azimuth: 177.25,
        elevation: -54.55,
        ra: 210.51676046,
        dec: -35.31140339,
        timestamp: 1713356804,
        eclipsed: true,
      },
    ],
  },
];


https://api.mapbox.com/styles/v1/mapbox/satellite-v9/static/0,0,1/1280x720?access_token=pk.eyJ1IjoiZmF6b2xpbiIsImEiOiJjbHYxOGRsc3kwMjVqMmpwbGs5enVvaDV6In0.AEREHqyz7XyuOgECG1PJKw